"""add message_id to episodic_memory

Revision ID: 2c5c686c8540
Revises: d2345a47a5bd
Create Date: 2026-08-08 01:52:01.744121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5c686c8540'
down_revision: Union[str, Sequence[str], None] = 'd2345a47a5bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodic_memory', sa.Column('message_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'episodic_memory', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'episodic_memory', type_='foreignkey')
    op.drop_column('episodic_memory', 'message_id')
    # ### end Alembic commands ###
