"""add source memory id to journeys

Revision ID: 52de351c296c
Revises: b650c6963515
Create Date: 2026-08-18 10:48:17.438756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52de351c296c'
down_revision: Union[str, Sequence[str], None] = 'b650c6963515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journeys', sa.Column('source_memory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'journeys', 'user_memory', ['source_memory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journeys', type_='foreignkey')
    op.drop_column('journeys', 'source_memory_id')
    # ### end Alembic commands ###
