"""change Journey Challenge model

Revision ID: 6d655aa8b6aa
Revises: 210ae28ee326
Create Date: 2026-08-13 09:14:55.695084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d655aa8b6aa'
down_revision: Union[str, Sequence[str], None] = '210ae28ee326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journey_challenges', sa.Column('skip_reason', sa.String(), nullable=True))
    op.add_column('journey_challenges', sa.Column('skip_reason_detail', sa.Text(), nullable=True))
    op.add_column('journey_challenges', sa.Column('difficulty_feedback', sa.String(), nullable=True))
    op.add_column('journey_challenges', sa.Column('emotional_response', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journey_challenges', 'emotional_response')
    op.drop_column('journey_challenges', 'difficulty_feedback')
    op.drop_column('journey_challenges', 'skip_reason_detail')
    op.drop_column('journey_challenges', 'skip_reason')
    # ### end Alembic commands ###
