"""cascade conversation derived data deletes

Revision ID: 771292451f53
Revises: 52de351c296c
Create Date: 2026-09-28 11:25:50.985022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771292451f53'
down_revision: Union[str, Sequence[str], None] = '52de351c296c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('behavior_observations_session_id_fkey'), 'behavior_observations', type_='foreignkey')
    op.drop_constraint(op.f('behavior_observations_message_id_fkey'), 'behavior_observations', type_='foreignkey')
    op.create_foreign_key(None, 'behavior_observations', 'conversation_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'behavior_observations', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('conversation_emotions_message_id_fkey'), 'conversation_emotions', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_emotions', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('episodic_memory_message_id_fkey'), 'episodic_memory', type_='foreignkey')
    op.drop_constraint(op.f('episodic_memory_session_id_fkey'), 'episodic_memory', type_='foreignkey')
    op.create_foreign_key(None, 'episodic_memory', 'conversation_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'episodic_memory', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_memory_evidence_episodic_memory_id_fkey'), 'user_memory_evidence', type_='foreignkey')
    op.create_foreign_key(None, 'user_memory_evidence', 'episodic_memory', ['episodic_memory_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_memory_evidence', type_='foreignkey')
    op.create_foreign_key(op.f('user_memory_evidence_episodic_memory_id_fkey'), 'user_memory_evidence', 'episodic_memory', ['episodic_memory_id'], ['id'])
    op.drop_constraint(None, 'episodic_memory', type_='foreignkey')
    op.drop_constraint(None, 'episodic_memory', type_='foreignkey')
    op.create_foreign_key(op.f('episodic_memory_session_id_fkey'), 'episodic_memory', 'conversation_sessions', ['session_id'], ['id'])
    op.create_foreign_key(op.f('episodic_memory_message_id_fkey'), 'episodic_memory', 'messages', ['message_id'], ['id'])
    op.drop_constraint(None, 'conversation_emotions', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_emotions_message_id_fkey'), 'conversation_emotions', 'messages', ['message_id'], ['id'])
    op.drop_constraint(None, 'behavior_observations', type_='foreignkey')
    op.drop_constraint(None, 'behavior_observations', type_='foreignkey')
    op.create_foreign_key(op.f('behavior_observations_message_id_fkey'), 'behavior_observations', 'messages', ['message_id'], ['id'])
    op.create_foreign_key(op.f('behavior_observations_session_id_fkey'), 'behavior_observations', 'conversation_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
