"""make emotion notes nullable

Revision ID: 8897362aa53b
Revises: 6fb55fe076d1
Create Date: 2026-07-19 08:09:39.746384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8897362aa53b'
down_revision: Union[str, Sequence[str], None] = '6fb55fe076d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emotion_analysis', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emotion_analysis', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
