"""remove analysis status from user memory

Revision ID: ad37d2be2c5d
Revises: 0523ebf0d098
Create Date: 2026-07-20 13:01:37.909896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad37d2be2c5d'
down_revision: Union[str, Sequence[str], None] = '0523ebf0d098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_memory', 'analysis_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_memory', sa.Column('analysis_status', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
