"""add user memory versioning and evidence tables

Revision ID: bc2e7f4efa63
Revises: 2c5c686c8540
Create Date: 2026-08-08 02:21:22.337469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2e7f4efa63'
down_revision: Union[str, Sequence[str], None] = '2c5c686c8540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_memory_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_memory_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_memory_id'], ['user_memory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_memory_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_memory_id', sa.Integer(), nullable=False),
    sa.Column('episodic_memory_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['episodic_memory_id'], ['episodic_memory.id'], ),
    sa.ForeignKeyConstraint(['user_memory_id'], ['user_memory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_memory', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_memory', 'version')
    op.drop_table('user_memory_evidence')
    op.drop_table('user_memory_history')
    # ### end Alembic commands ###
