"""add pgvector embedding to episodic memory

Revision ID: cdc3c461f0fd
Revises: bc2e7f4efa63
Create Date: 2026-08-08 05:48:12.972475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'cdc3c461f0fd'
down_revision: Union[str, Sequence[str], None] = 'bc2e7f4efa63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodic_memory', sa.Column('embedding', Vector(768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodic_memory', 'embedding')
    # ### end Alembic commands ###
