"""add episodic_memory table

Revision ID: d2345a47a5bd
Revises: f439a14f1284
Create Date: 2026-08-08 01:38:24.384394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2345a47a5bd'
down_revision: Union[str, Sequence[str], None] = 'f439a14f1284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodic_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("event_type IN ('emotion', 'behavior')", name='check_episodic_memory_event_type'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='check_episodic_memory_confidence'),
    sa.CheckConstraint('importance >= 0 AND importance <= 1', name='check_episodic_memory_importance'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episodic_memory')
    # ### end Alembic commands ###
