"""make message feedback message id required

Revision ID: d90268197dfd
Revises: eecf4aea4919
Create Date: 2026-08-12 02:43:20.803310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90268197dfd'
down_revision: Union[str, Sequence[str], None] = 'eecf4aea4919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_feedback', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('message_feedback_message_id_fkey'), 'message_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'message_feedback', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_feedback', type_='foreignkey')
    op.create_foreign_key(op.f('message_feedback_message_id_fkey'), 'message_feedback', 'messages', ['message_id'], ['id'])
    op.alter_column('message_feedback', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
