"""add conversation analysis tables

Revision ID: ea5ad01b3e63
Revises: fc1fbba93968
Create Date: 2026-08-02 03:21:45.984210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5ad01b3e63'
down_revision: Union[str, Sequence[str], None] = 'fc1fbba93968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("\n            tag IN (\n                'fear_of_judgment',\n                'avoiding_social_expression',\n                'overthinking',\n                'low_confidence',\n                'social_avoidance',\n                'seeking_validation',\n                'conflict_avoidance'\n            )\n            ", name='check_behavior_observation_tag'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emotion', sa.String(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("\n            emotion IN (\n                'anxiety',\n                'confidence',\n                'fear',\n                'excitement',\n                'frustration',\n                'sadness',\n                'shame',\n                'hope'\n            )\n            ", name='check_conversation_emotion'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_memory', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('user_memory', sa.Column('evidence_count', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_memory', 'evidence_count')
    op.drop_column('user_memory', 'source_type')
    op.drop_table('conversation_emotions')
    op.drop_table('behavior_observations')
    # ### end Alembic commands ###
