"""add confidence to user-memory

Revision ID: f439a14f1284
Revises: ea5ad01b3e63
Create Date: 2026-08-06 00:26:23.575739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f439a14f1284'
down_revision: Union[str, Sequence[str], None] = 'ea5ad01b3e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_memory', sa.Column('confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_memory', 'confidence')
    # ### end Alembic commands ###
