"""add onboarding fields

Revision ID: f87f863141b4
Revises: a1be3688fb6e
Create Date: 2026-07-28 00:51:18.434301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87f863141b4'
down_revision: Union[str, Sequence[str], None] = 'a1be3688fb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_memory', sa.Column('tag', sa.String(), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('user_memory', 'tag')
    # ### end Alembic commands ###
